namespace BankingAppCS
{
    partial class Form1
    {
        /// <summary>
        ///  Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        ///  Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        ///  Required method for Designer support - do not modify
        ///  the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            label1 = new Label();
            label2 = new Label();
            label3 = new Label();
            label4 = new Label();
            label5 = new Label();
            label6 = new Label();
            txtName = new TextBox();
            txtAcc = new TextBox();
            txtBalane = new TextBox();
            txtAdd = new TextBox();
            dtDate = new DateTimePicker();
            label7 = new Label();
            btnDeposit = new Button();
            btnWithd = new Button();
            btnShow = new Button();
            SuspendLayout();
            // 
            // label1
            // 
            label1.AutoSize = true;
            label1.Font = new Font("Segoe UI", 14F);
            label1.Location = new Point(110, 53);
            label1.Name = "label1";
            label1.Size = new Size(44, 152);
            label1.TabIndex = 0;
            label1.Text = "ID\r\n\r\n\r\n\r\n";
            // 
            // label2
            // 
            label2.AutoSize = true;
            label2.Font = new Font("Segoe UI", 14F);
            label2.Location = new Point(110, 128);
            label2.Name = "label2";
            label2.Size = new Size(91, 38);
            label2.TabIndex = 1;
            label2.Text = "Name";
            // 
            // label3
            // 
            label3.AutoSize = true;
            label3.Font = new Font("Segoe UI", 14F);
            label3.Location = new Point(110, 206);
            label3.Name = "label3";
            label3.Size = new Size(116, 38);
            label3.TabIndex = 2;
            label3.Text = "Address";
            // 
            // label4
            // 
            label4.AutoSize = true;
            label4.Font = new Font("Segoe UI", 14F);
            label4.Location = new Point(110, 287);
            label4.Name = "label4";
            label4.Size = new Size(112, 38);
            label4.TabIndex = 3;
            label4.Text = "Balance";
            // 
            // label5
            // 
            label5.AutoSize = true;
            label5.Font = new Font("Segoe UI", 14F);
            label5.Location = new Point(110, 362);
            label5.Name = "label5";
            label5.Size = new Size(75, 38);
            label5.TabIndex = 4;
            label5.Text = "Date";
            // 
            // label6
            // 
            label6.AutoSize = true;
            label6.Font = new Font("Segoe UI", 14F);
            label6.Location = new Point(110, 444);
            label6.Name = "label6";
            label6.Size = new Size(228, 38);
            label6.TabIndex = 5;
            label6.Text = "Account Number";
            // 
            // txtName
            // 
            txtName.Font = new Font("Segoe UI", 14F);
            txtName.Location = new Point(372, 121);
            txtName.Name = "txtName";
            txtName.Size = new Size(347, 45);
            txtName.TabIndex = 6;
            // 
            // txtAcc
            // 
            txtAcc.Font = new Font("Segoe UI", 14F);
            txtAcc.Location = new Point(372, 441);
            txtAcc.Name = "txtAcc";
            txtAcc.Size = new Size(347, 45);
            txtAcc.TabIndex = 7;
            txtAcc.Text = "Auto Generated By System";
            // 
            // txtBalane
            // 
            txtBalane.Font = new Font("Segoe UI", 14F);
            txtBalane.Location = new Point(372, 280);
            txtBalane.Name = "txtBalane";
            txtBalane.Size = new Size(347, 45);
            txtBalane.TabIndex = 8;
            // 
            // txtAdd
            // 
            txtAdd.Font = new Font("Segoe UI", 14F);
            txtAdd.Location = new Point(372, 199);
            txtAdd.Name = "txtAdd";
            txtAdd.Size = new Size(347, 45);
            txtAdd.TabIndex = 9;
            // 
            // dtDate
            // 
            dtDate.Font = new Font("Segoe UI", 14F);
            dtDate.Location = new Point(372, 362);
            dtDate.Name = "dtDate";
            dtDate.Size = new Size(461, 45);
            dtDate.TabIndex = 10;
            // 
            // label7
            // 
            label7.AutoSize = true;
            label7.Font = new Font("Segoe UI", 14F);
            label7.Location = new Point(372, 53);
            label7.Name = "label7";
            label7.Size = new Size(347, 38);
            label7.TabIndex = 11;
            label7.Text = "Auto Generated By System";
            // 
            // btnDeposit
            // 
            btnDeposit.BackColor = SystemColors.Highlight;
            btnDeposit.Font = new Font("Segoe UI", 14F);
            btnDeposit.ForeColor = SystemColors.HighlightText;
            btnDeposit.Location = new Point(110, 532);
            btnDeposit.Name = "btnDeposit";
            btnDeposit.Size = new Size(125, 48);
            btnDeposit.TabIndex = 12;
            btnDeposit.Text = "Deposit";
            btnDeposit.UseVisualStyleBackColor = false;
            btnDeposit.Click += btnDeposit_Click;
            // 
            // btnWithd
            // 
            btnWithd.BackColor = SystemColors.Highlight;
            btnWithd.Font = new Font("Segoe UI", 14F);
            btnWithd.ForeColor = SystemColors.ButtonHighlight;
            btnWithd.Location = new Point(372, 532);
            btnWithd.Name = "btnWithd";
            btnWithd.Size = new Size(150, 48);
            btnWithd.TabIndex = 13;
            btnWithd.Text = "Withdraw";
            btnWithd.UseVisualStyleBackColor = false;
            // 
            // btnShow
            // 
            btnShow.BackColor = SystemColors.Info;
            btnShow.Font = new Font("Segoe UI", 14F);
            btnShow.ForeColor = SystemColors.WindowText;
            btnShow.Location = new Point(647, 532);
            btnShow.Name = "btnShow";
            btnShow.Size = new Size(112, 48);
            btnShow.TabIndex = 14;
            btnShow.Text = "Show";
            btnShow.UseVisualStyleBackColor = false;
            // 
            // Form1
            // 
            AutoScaleDimensions = new SizeF(10F, 25F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = SystemColors.GradientInactiveCaption;
            ClientSize = new Size(937, 712);
            Controls.Add(btnShow);
            Controls.Add(btnWithd);
            Controls.Add(btnDeposit);
            Controls.Add(label7);
            Controls.Add(dtDate);
            Controls.Add(txtAdd);
            Controls.Add(txtBalane);
            Controls.Add(txtAcc);
            Controls.Add(txtName);
            Controls.Add(label6);
            Controls.Add(label5);
            Controls.Add(label4);
            Controls.Add(label3);
            Controls.Add(label2);
            Controls.Add(label1);
            Name = "Form1";
            Text = "Banking App";
            Load += Form1_Load;
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private Label label1;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private TextBox txtName;
        private TextBox txtAcc;
        private TextBox txtBalane;
        private TextBox txtAdd;
        private DateTimePicker dtDate;
        private Label label7;
        private Button btnDeposit;
        private Button btnWithd;
        private Button btnShow;
    }
}
